### PR TITLE
Move LLVM OCaml-Kaleidoscope tutorial to llvm-archive

### PR DESCRIPTION
**Pull request by xgupta**
It seems Ocaml-Kaleidoscope/ tutorial is not [updated from the last 10 years](https://github.com/llvm/llvm-project/commits/main/llvm/examples/OCaml-Kaleidoscope) (the last fix was on Fab 10, 2011). It does not validate itself with the tests. It seems no-one maintaining Ocaml. 
Also, @whitequark once a maintainer of LLVM OCaml binding give permission to move the tutorial in [this](https://reviews.llvm.org/D96299) Phabricator Revision.

### CODE REVIEW

**Comment by geexie** [comment]
@xgupta, I'm just curious what is the reason from moving this away of main llvm-project? 

This example compiles and runs for me. Is something changed in LLVM+OCaml binging over those 10 years?

**Comment by xgupta** [comment]
>I'm just curious what is the reason from moving this away of main llvm-project?

* Don't have build system. autoconf removed but cmake was added.
* Don't have any testcase. 

> This example compiles and runs for me.

That is really nice. How do you compiling it? I mean what was your `ocamlbuild` invocation for chapter 4.

I  am sorry if I have committed early. You are invited to revert the revision. And update the build instructions if need.

**Comment by xgupta** [comment]
@geexie in case you don't have commit access, I will revert the revision. 

If the example is correctly building I am happy to put effort to add CMake build files and test cases.

**Comment by geexie** [comment]
@xgupta, Thanks for your responsiveness! I'm happy to make a PR with revert. I just wanted to double check if it still work since I toyed with it some time around Christmas.

**Comment by xgupta** [comment]
Seems this is not needed. And there is someone else also asking to same question here - https://llvm.discourse.group/t/why-kaleidoscope-tutorial-in-ocaml-is-removed/4278. I am closing it here. And will wait as the person in the above thread will update tutorial and upload a new review on phabricator.

**Comment by geexie** [comment]
@xgupta, glad to hear! And shame on me for completely forgetting this thread.

**Pull request closed without merging**
